name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-lastest
    steps:
    - uses: acions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python3 manage.py test
